name: PullRequest tests

on:
  pull_request:
    branches:
      - master
      - dev
      - '!renovate/**'
jobs:
  pull_request_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Build project
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14'

      - uses: actions/cache@v2.1.7
        id: cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-node${{ env.node-version }}

      - run: sudo npm install --global cross-env

      - name: Run tests
        run: |
          npm ci
          npm test

